### ISSUE TITLE
App logo breaks title ?

### ISSUE THREAD

**Issue by sylvinus** [joshfire-platform-templates/event#3]
Cf National Geographic demo

**Comment by steren** [comment]
Currently, if the app logo is set, then it is used in the top bar. Text title is only here is no app logo.

In the demo, since I set an app logo, it appeared in the top bar.

**Comment by sylvinus** [comment]
ok then I think it had a display bug ? (too much height ?)

**Comment by steren** [comment]
The logo is supposed to fill the height of the topbar. It was the case I think.
It works well for TEDxConcorde, where the app logo is a transparent png rectangle, and this is the guideline
